# Generated by Django 3.2.9 on 2021-11-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_income', models.CharField(max_length=100, null=True)),
                ('your_expenses', models.CharField(max_length=100, null=True)),
                ('your_electricity_expense', models.CharField(max_length=100, null=True)),
                ('your_investment', models.CharField(max_length=100, null=True)),
                ('your_food', models.CharField(max_length=100, null=True)),
                ('your_emi', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
