# Generated by Django 3.2.9 on 2021-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forminput',
            name='your_electricity_expense',
        ),
        migrations.RemoveField(
            model_name='forminput',
            name='your_emi',
        ),
        migrations.RemoveField(
            model_name='forminput',
            name='your_food',
        ),
        migrations.RemoveField(
            model_name='forminput',
            name='your_investment',
        ),
        migrations.AlterField(
            model_name='forminput',
            name='your_expenses',
            field=models.IntegerField(null=True),
        ),
    ]
