# Generated by Django 3.2.9 on 2021-11-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211105_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forminput',
            old_name='amount',
            new_name='your_expenses',
        ),
        migrations.RenameField(
            model_name='forminput',
            old_name='field',
            new_name='your_income',
        ),
    ]
