# Generated by Django 3.2.9 on 2021-11-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211105_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forminput',
            old_name='your_expenses',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='forminput',
            old_name='your_income',
            new_name='Field',
        ),
    ]
