# Generated by Django 3.2.9 on 2021-11-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211104_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forminput',
            old_name='your_expenses',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='forminput',
            old_name='your_income',
            new_name='field',
        ),
    ]
